name: social_app_dalia
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  page_transition: ^2.0.9
  provider: ^6.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/daliaLogo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
